[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "intchem"
version = "0.2.0"
description = "Integer chemistry composition enumeration"
authors = [{name="Hiori Kino"}]
dependencies = [
    "pymatgen",
    "pandas",
    "pytest",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
